In [1]:
## From SQL to DataFrame Pandas
import pandas as pd
import pyodbc

In [2]:
sql_conn = pyodbc.connect('DRIVER={SQL Server Native Client 11.0}; \
                            SERVER=192.168.1.232\SRV19; \
                            DATABASE=FinCrimeStaging; \
                            Trusted_Connection=yes') 
query = "SELECT * FROM [FinCrimeStaging].[dbo].[SAMPLE_TRANS_GIFTS_FORMAT]"

In [3]:
df = pd.read_sql(query, sql_conn)

In [4]:
df.head()

,Reference number,Transaction Code,Transaction Amount,Original Amount,Currency code,Transaction / Payment Date,Debit Party Type,Debit Party ID3.6,Debit Party Name 2.5,Debit Party Addr 13.6,...,Cover Bank to Bank Information 14.1,Cover Bank to Bank Information 24.1,Cover Bank to Bank Information 34.1,Cover Bank to Bank Information 44.1,Cover Bank to Bank Information 54.1,Cover Bank to Bank Information 64.1,Cover Payment Instructed Amount4.1,Check Image Link 4.3,Addnt Payment Info Type,Addnt Payment Info
0,CFMSPACH4766498,CFSB_ODFI_ACH22,65.0,65.0,USD,2019-03-26,None,CFSBCK715500314,AIRWALLEX HK LTD ORIG,None,...,None,None,None,None,None,None,None,None,None,None
1,CFMSPACH4766499,CFSB_ODFI_ACH22,65.0,65.0,USD,2019-03-26,None,CFSBCK715500314,AIRWALLEX HK LTD ORIG,None,...,None,None,None,None,None,None,None,None,None,None
2,CFMSPACH4766500,CFSB_ODFI_ACH22,65.0,65.0,USD,2019-03-26,None,CFSBCK715500314,AIRWALLEX HK LTD ORIG,None,...,None,None,None,None,None,None,None,None,None,None
3,CFMSPACH4766583,CFSB_ODFI_ACH22,4000.0,4000.0,USD,2019-03-26,None,CFSBCK715100400,CURRENXIE LTD,None,...,None,None,None,None,None,None,None,None,None,None
4,CFMSPACH4766585,CFSB_ODFI_ACH22,1152.0,1152.0,USD,2019-03-26,None,CFSBCK715100400,CURRENXIE LTD,None,...,None,None,None,None,None,None,None,None,None,None

In [16]:
import pandas_profiling
#Generate profile report using pandas_profiling
report = pandas_profiling.ProfileReport(df)

In [17]:
#covert profile report as html file
report.to_file("D:\GIT\DataProfiling\SAMPLE_TRANS_GIFTS_FORMAT.html")